[2025-04-14T22:00:10.770+0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-14T22:00:10.775+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_trends_etl_pipeline.extract_google_trends_data manual__2025-04-14T13:47:18.677732+00:00 [queued]>
[2025-04-14T22:00:10.777+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_trends_etl_pipeline.extract_google_trends_data manual__2025-04-14T13:47:18.677732+00:00 [queued]>
[2025-04-14T22:00:10.777+0800] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-04-14T22:00:10.790+0800] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_google_trends_data> on 2025-04-14 13:47:18.677732+00:00
[2025-04-14T22:00:10.792+0800] {standard_task_runner.py:72} INFO - Started process 12238 to run task
[2025-04-14T22:00:10.794+0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'google_trends_etl_pipeline', 'extract_google_trends_data', 'manual__2025-04-14T13:47:18.677732+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/google_trends_dag.py', '--cfg-path', '/tmp/tmpusw66rw7']
[2025-04-14T22:00:10.795+0800] {standard_task_runner.py:105} INFO - Job 63: Subtask extract_google_trends_data
[2025-04-14T22:00:10.822+0800] {task_command.py:467} INFO - Running <TaskInstance: google_trends_etl_pipeline.extract_google_trends_data manual__2025-04-14T13:47:18.677732+00:00 [running]> on host Conglaptop.
[2025-04-14T22:00:10.858+0800] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='google_trends_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_google_trends_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-14T13:47:18.677732+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-14T13:47:18.677732+00:00'
[2025-04-14T22:00:10.859+0800] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-14T22:00:10.859+0800] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-14T22:00:10.859+0800] {logging_mixin.py:190} INFO - Current task name:extract_google_trends_data state:running start_date:2025-04-14 14:00:10.775235+00:00
[2025-04-14T22:00:10.859+0800] {logging_mixin.py:190} INFO - Dag name:google_trends_etl_pipeline and current dag run status:running
[2025-04-14T22:00:10.859+0800] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-14T22:00:10.860+0800] {logging_mixin.py:190} INFO - 2025-04-01 00:00:00
[2025-04-14T22:00:10.860+0800] {logging_mixin.py:190} INFO - 2025-02-28 00:00:00
[2025-04-14T22:00:11.781+0800] {logging_mixin.py:190} INFO - {'version': '0.1.20241227', 'status_code': 20000, 'status_message': 'Ok.', 'time': '0.0944 sec.', 'cost': 0.00225, 'tasks_count': 1, 'tasks_error': 0, 'tasks': [{'id': '04141700-9519-0170-0000-1c67142584e7', 'status_code': 20100, 'status_message': 'Task Created.', 'time': '0.0098 sec.', 'cost': 0.00225, 'result_count': 0, 'path': ['v3', 'keywords_data', 'google_trends', 'explore', 'task_post'], 'data': {'api': 'keywords_data', 'function': 'explore', 'se': 'google_trends', 'date_from': '2025-03-01', 'date_to': '2025-04-05', 'keywords': ['Singapore', 'Thailand', 'Malaysia', 'Indonesia', 'Vietnam'], 'category_code': 67}, 'result': None}]}
[2025-04-14T22:00:12.690+0800] {logging_mixin.py:190} INFO - {'version': '0.1.20241227', 'status_code': 20000, 'status_message': 'Ok.', 'time': '0.1067 sec.', 'cost': 0.00225, 'tasks_count': 1, 'tasks_error': 0, 'tasks': [{'id': '04141700-9519-0170-0000-72672e1b76cc', 'status_code': 20100, 'status_message': 'Task Created.', 'time': '0.0167 sec.', 'cost': 0.00225, 'result_count': 0, 'path': ['v3', 'keywords_data', 'google_trends', 'explore', 'task_post'], 'data': {'api': 'keywords_data', 'function': 'explore', 'se': 'google_trends', 'date_from': '2025-03-01', 'date_to': '2025-04-05', 'keywords': ['Singapore', 'Philippines', 'Cambodia', 'Myanmar'], 'category_code': 67}, 'result': None}]}
[2025-04-14T22:00:13.560+0800] {logging_mixin.py:190} INFO - {'version': '0.1.20241227', 'status_code': 20000, 'status_message': 'Ok.', 'time': '0.0676 sec.', 'cost': 0.00225, 'tasks_count': 1, 'tasks_error': 0, 'tasks': [{'id': '04141700-9519-0170-0000-00a6a566e018', 'status_code': 20100, 'status_message': 'Task Created.', 'time': '0.0050 sec.', 'cost': 0.00225, 'result_count': 0, 'path': ['v3', 'keywords_data', 'google_trends', 'explore', 'task_post'], 'data': {'api': 'keywords_data', 'function': 'explore', 'se': 'google_trends', 'date_from': '2025-03-01', 'date_to': '2025-04-05', 'keywords': ['Singapore', 'Laos', 'Brunei'], 'category_code': 67}, 'result': None}]}
[2025-04-14T22:00:13.561+0800] {logging_mixin.py:190} INFO - Waiting 60 seconds for tasks to complete...
[2025-04-14T22:01:14.736+0800] {logging_mixin.py:190} INFO - 1
[2025-04-14T22:01:14.737+0800] {logging_mixin.py:190} INFO - []
[2025-04-14T22:01:14.738+0800] {logging_mixin.py:190} INFO - Results fetched successfully.
[2025-04-14T22:01:14.742+0800] {logging_mixin.py:190} INFO - No data was retrieved. Please check if the tasks returned any results.
[2025-04-14T22:01:14.742+0800] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/airflow/dags/google_trends_dag.py", line 79, in extract_google_trends_data
    raise ValueError("No Google Trends data was extracted")
ValueError: No Google Trends data was extracted
[2025-04-14T22:01:14.745+0800] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-14T22:01:14.745+0800] {logging_mixin.py:190} INFO - Task start:2025-04-14 14:00:10.775235+00:00 end:2025-04-14 14:01:14.745098+00:00 duration:63.969863
[2025-04-14T22:01:14.745+0800] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_google_trends_data> dag:<DAG: google_trends_etl_pipeline> dagrun:<DagRun google_trends_etl_pipeline @ 2025-04-14 13:47:18.677732+00:00: manual__2025-04-14T13:47:18.677732+00:00, state:running, queued_at: 2025-04-14 13:47:18.687828+00:00. externally triggered: True>
[2025-04-14T22:01:14.745+0800] {logging_mixin.py:190} INFO - Failure caused by No Google Trends data was extracted
[2025-04-14T22:01:14.745+0800] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=google_trends_etl_pipeline, task_id=extract_google_trends_data, run_id=manual__2025-04-14T13:47:18.677732+00:00, execution_date=20250414T134718, start_date=20250414T140010, end_date=20250414T140114
[2025-04-14T22:01:14.772+0800] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-14T22:01:14.773+0800] {standard_task_runner.py:124} ERROR - Failed to execute job 63 for task extract_google_trends_data (No Google Trends data was extracted; 12238)
Traceback (most recent call last):
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/airflow/dags/google_trends_dag.py", line 79, in extract_google_trends_data
    raise ValueError("No Google Trends data was extracted")
ValueError: No Google Trends data was extracted
[2025-04-14T22:01:14.795+0800] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-14T22:01:14.805+0800] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-14T22:01:14.813+0800] {local_task_job_runner.py:245} INFO - ::endgroup::
